url: http://rachelcdavies.github.io
baseurl: ""

# Site Settings
title: rachelcdavies
description: "Rachel C Davies Home"
author: "Rachel C Davies"

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.md"]