# Site settings
title: Thoughts on Agile Coaching
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on Agile Coaching
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rachelcdavies.github.io" # the base hostname & protocol for your site

twitter_username: rachelcdavies
github_username:  rachelcdavies

exclude: ["Gemfile", "Gemfile.lock", "README.md"] # files to exclude

# Build settings
markdown: kramdown
